my_string = input("Give me any string, and I'll do something with it!\n")
print("The length of your string is: {}".format(len(my_string)))
print(my_string.upper())
print(my_string.lower())
print("".join(my_string.split()))
print(my_string[0])
print(my_string[-1])